---
title: "RWorksheet_Tamayor#3a"
output: pdf_document
date: "2023-10-04"
---








LETTERS

UppercaseLetter <- LETTERS [1:26]
UppercaseLetter

letters

LowercaseLetter <- letters [1:26]
LowercaseLetter

LETTERS

#a.first 11 letters

first11letters <- LETTERS [1:11]
first11letters

#b. odd numbered letters

oddnumberletters <- LETTERS[seq(from=1, to=length (LETTERS),by=2)]
oddnumberletters

#c. vowels

vowels <- LETTERS[c(1,5,9,15,21)]
vowels

#d. last 5 lowercase letter

LowercaseLetter <- letters [22:26]
LowercaseLetter

#e letters between 15 to 24 letters in lowercase

LowercaseLetter <- letters[15:24]
LowercaseLetter

#2. average temperatures in April for Tuguegarao City, Manila, Iloilo City, Tacloban, Samal Island, and Davao City. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees.

#a. Creating a character vector for the city/town

city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
city

#output
[1] "Tuguegarao City" "Manila" "Iloilo City" "Tacloban" "Samal Island" "Davao City"

#b. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees.

temp <- c(42, 39, 34, 34, 30, 27)
temp

#output
[1] 42 39 34 34 30 27

#c. dataframe to combine the city and the temp 

city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")

temps <- c(42, 39, 34, 34, 30, 27)

citytemp <- data.frame (
  
            city = c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City"),
            temp = c(42, 39, 34, 34, 30, 27)
)

citytemp
View(citytemp)

#d. Associate the dataframe you have created in 2.(c)


names(citytemp) <- c ("City", "Temperature")
citytemp

#e. print the structure

print(str(citytemp))
#The output diplayed that there are 6 observations of 2 variables.

#f. what is the content of row 3 and row 4

row3_4 <- citytemp [3:4,]
row3_4


#g.  highest and lowest temperature

highest_temp <-citytemp [which.max(citytemp$Temperature),]
highest_temp


lowest_temp <-citytemp [which.min(citytemp$Temperature),]
lowest_temp


#using matrices

# row = 2
matrix(c(5,6,7,4,3,2,1,2,3,7,8,9),nrow = 2)

# row = 3 and column = 2
matrix(data = c(3,4,5,6,7,8),3,2)

# creating a diagonal matrix where x value will always be 1
diag(1,nrow = 6,ncol = 5)

diag(6)



#2. Create a matrix of one to eight and eleven to fourteen with four columns and three rows.

#a. What will be the R code for the #2 question and its result?

#row=3
matrix (c(1:8, 11:14),nrow=3)

#b. Multiply the matrix by two. What is its R code and its result?


matrix=matrix*2
matrix

#c. What is the content of row 2? What is its R code?

x2 <- matrix (c(1:8, 11:14),nrow=3)
x2


rowx2 <- x2[,2]
rowx2

#d. What will be the R code if you want to display the column 3 and column 4 in row 1 and row 2? What is its output?

x2 <- x2[1:2,3:4]
x2

#e. What is the R code is you want to display only the columns in 2 and 3, row 3? What is its output?

subsetx2 <- x2[3,2:3]
subsetx2


#f. What is the R code is you want to display only the columns 4? What is its output?

colx2 <- x2[,4]
colx2


#g. Name the rows as isa, dalawa, tatlo and columns as uno, dos, tres, quatro for the matrix that was created in b.‘. What is its R code and corresponding output?


mat <-matrix (c(1:8, 11:14),nrow=3)

rownames(mat) <- c ("isa","dalawa","tatlo")
colnames(mat) <- c ("uno","dos","tres","quatro")
print(mat)

#h. From the original matrix you have created in a, reshape the matrix by assigning a new dimension with dim(). New dimensions should have 2 columns and 6 rows. What will be the R code and its output?


mat <- matrix (mat,nrow=6, ncol=2)
mat


#Using Arrays

# creates a two-dimensional array containing numbers from 1 to 24 that have 3 rows and 4 columns

array_dta <- array(c(1:24), c(3,4,2))
array_dta


# checking for the dimensions
# row, column, dimension

dim(array_dta)

#checking for the number of elements

length(array_dta)

• Another way to create arrays
vectorA <- c(1:24)

# creating an array

an_Array <- array(vectorA, dim = c(3,4,2))
an_Array



#a. Create an array for the above numeric values. Each values will be repeated twice What will be the R code if you are to create a three-dimensional array with 4 columns and 2 rows. What will be its output?

#3. An array contains 1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1

vectorA <- c(1,2,3,6,7,8,9,0,3,4,5,1)

array <- array(vectorA, dim=c(2,4,3))
array

#b. How may dimensions do your array have?

dim(array)

#c. c. Name the rows as lowercase letters and columns as uppercase letters starting from the A. The array names should be “1st-Dimensional Array”, “2nd-Dimensional Array”, and “3rd-Dimensional Array”. What will be the R codes and its output?

colnames(array) <- c ("A","B","C","D")
rownames(array) <- c ("a","b")

array




