---
title: "RWorksheet_Tamayor#3b.Rmd"
author: "Ross Camille Tamayor BSIT2C"
date: "2023-11-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

#1. 
#a. 

 library(readxl) 
 Household Data.csv <- read_excel(“Household Data.csv”)
 View(Household Data.csv) Household Data.csv



household_data <- data.frame(
  Respond_1 = c(1:20),
  
  Sex = c("Female","Female","Male","Female","Female","Female","Female","Female","Female","Female","Male","Female","Female","Female","Female","Female","Female","Female","Male","Female"),
  
  FatherOccupation = c("Farmer","Others","Others","Others","Farmer","Driver","Others","Farmer","Farmer","Farmer","Others","Driver","Farmer","Others","Others","Farmer","Others","Farmer","Driver","Farmer"),
  
  Person = c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6),
  
  Siblings = c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2),
  
  Typesofhouse = c("Wood","Semi-Concrete","Concrete","Wood","Wood","Concrete","Concrete","Wood","Semi-Concrete","Concrete","Semi-Concrete","Concrete","Semi-Concrete","Semi-Concrete","Concrete","Concrete","Concrete","Concrete","Concrete","Semi-Concrete")
  
)
household_data

#1b.

summary(household_data)

#1c.
mean_siblings <- mean(household_data$Siblingsatschool)
is_mean_5 <- mean_siblings == 5
print(is_mean_5)

#No, because the mean is 2.95.

#1d.
firsttworowsallcolumns <- household_data[1:2, ]
print(firsttworowsallcolumns)

#1e.
selected_rows_columns <- household_data[c(3, 5), c(2, 4)]
print(selected_rows_columns)

#1f.
types_houses <- household_data$Typeshouse

#1g.
male_farmers <- household_data[household_data$Sex == "Male" & household_data$FatherOccupation == "Farmer", ]
print(male_farmers)

#1h.

female_greater_than_5_siblings <- household_data[household_data$Sex == "Female" & household_data$Siblingsatschool >= 5, ]
print(female_greater_than_5_siblings)

#2
df <- data.frame(
  Ints = integer(0),
  Doubles = double(0),
  Characters = character(0),
  Logicals = logical(0),
  Factors = factor(NA, levels = character(0)),
  stringsAsFactors = FALSE
)

print("Structure of the empty dataframe:")
str(df)

#2a. The data frame has no data.

#3
household_data <- data.frame(
  Respondents = c(1:10),
  Sex = c("Male", "Female", "Female", "Male", "Male", "Female", "Female", "Male", "Female", "Male"),
  FatherOccupation = c(1, 2, 3, 3, 1, 2, 2, 3, 1, 3),
  PersonatHome = c(5, 7, 3, 8, 6, 4, 4, 2, 11, 6),
  Siblingsatschool = c(2, 3, 0, 5, 2, 3, 1, 2, 6, 2),
  Typeshouse = c("Wood", "Congrete", "Congrete", "Wood", "Semi-Congrete", "Semi-Congrete", "Wood", "Semi-Congrete", "Semi-Congrete", "Congrete")
)
household_data

#3a.
write.csv(household_data, file = "HouseholdData.csv", row.names = FALSE)

#3b.
imported_data <- read.csv("HouseholdData.csv")


#3b.(2)
imported_data$Sex <- factor(imported_data$Sex, levels = c("Male", "Female"))
imported_data$Sex <- as.integer(imported_data$Sex)

#3c.
imported_data$Typeshouse <- factor(imported_data$Typeshouse, levels = c("Wood", "Concrete", "Semi-Concrete"))
imported_data$Typeshouse <- as.integer(imported_data$Typeshouse)

#3d.
imported_data$FatherOccupation <- factor(imported_data$FatherOccupation, levels = c("Farmer", "Driver", "Others"))
imported_data$FatherOccupation <- as.integer(imported_data$FatherOccupation)

#3e.
female_drivers <- imported_data[imported_data$Sex == 2 & imported_data$FatherOccupation == 2, ]
print(female_drivers)

#3f.
greater_than_5_siblings <- imported_data[imported_data$Siblingsatschool >= 5, ]
print(greater_than_5_siblings)

#4. Interpret the graph 
In figure 3's graph it illustrates how daily attitudes of people affect our world in significant ways. In other words, we always allow ourselves to express our thoughts and the knowledge we acquire on a daily basis.



